Toast notification widget
ettibo/flutter-clean-archi pull request #36
Opened 2022-09-19 13:01 UTC by ZMontassar

Add a Custom Toast when we check internet connection and add a animation to the toast notification

2022-09-19 14:03 UTC, Hamitix requested changes

2022-09-19 14:03 UTC, Hamitix commented on lib/main_common.dart
> +  connectionStatusManager.activateConnectionManager();
Move all this code in a method named "activateConnectionStatusManager" in the "connection_check_status_manager.dart" in the "lib/managers".

2022-09-19 14:03 UTC, Hamitix commented on lib/shared/toast_utils.dart
> +import 'package:globo_fitness/main_common.dart';
Maybe use Dependancy Injection for "navigatorKey" to avoid importing the whole "main_common.dart" file

2022-09-19 14:03 UTC, Hamitix commented on lib/shared/toast_utils.dart
> +      context: navigatorKey.currentContext!,
Avoid force nullable "!".
Check if currentContext isn't null with the custom extension "nullable_check.dart"

2022-09-19 14:03 UTC, Hamitix commented on lib/shared/toast_utils.dart
> +}
Regroup this method into 1 => Use a bool for success & error

2022-09-19 14:03 UTC, Hamitix commented on lib/injection/managers_injection.dart
> +import 'package:globo_fitness/managers/connection_status_manager.dart';
Re-order all imports (for all edited files) with the guidelines.

2022-09-19 14:03 UTC, Hamitix commented on lib/managers/connection_check_status_manager.dart
>    static final ConnectionCheckStatusManager _connectionStatusSingleton =
Change the name of this file to "connection_status_manager_impl.dart" for implementation :)

2022-09-19 14:03 UTC, Hamitix commented on lib/managers/connection_check_status_manager.dart
> +        : showError("Vous n'êtes pas connecté");
Use translated string with the lib "easy_localizations".

2022-09-19 14:03 UTC, Hamitix commented on lib/managers/connection_check_status_manager.dart
> +  void setCheckInternetConnectionMsg(bool hasConnection) async {
Change the name of this function.
Maybe "showCustomAlert", "showAlert", etc ...

Also, this method doesn't seems to need to be async

2022-09-19 16:00 UTC, ZMontassar commented on lib/main_common.dart
> +  connectionStatusManager.activateConnectionManager();
Why ? I think it's useless to put all this code in a method named "activateConnectionStatusManager" in the "connection_check_status_manager.dart"

2022-09-19 16:27 UTC, ettibo commented on lib/injection/managers_injection.dart
> +      .inject<ConnectionStatusManagerImpl>(ConnectionCheckStatusManager());
should it not be the .inject<ConnectionStatusManager>(ConnectionCheckStatusManagerImp()); ?

2022-09-19 16:28 UTC, ettibo commented on lib/main_common.dart
> +  DependecyInjection.instance.get<ConnectionStatusManagerImpl>();
DependecyInjection.instance.get<ConnectionStatusManager>();

2022-09-19 16:30 UTC, ettibo commented on lib/managers/connection_status_manager_impl.dart
> +abstract class ConnectionStatusManagerImpl {
How can it be and Impl ?

2022-09-20 14:14 UTC, Hamitix requested changes

2022-09-20 14:14 UTC, Hamitix commented on lib/managers/connectionManager/connection_manager_impl.dart
> +  }
return => function

2022-09-20 14:14 UTC, Hamitix commented on assets/translations/en.json
> +        "succes_connexion_message": "You are connected to the internet",
Typo  => "success"

2022-09-20 14:14 UTC, Hamitix commented on lib/managers/connectionManager/connection_manager_impl.dart
arrow function =>

2022-09-20 14:14 UTC, Hamitix commented on lib/managers/connectionManager/connection_manager_impl.dart
> +    showAlertCheckInternetConnection(_hasConnection);
Rename to something more precise. Like "showPopupNewConnectionStatus" :)

2022-09-20 14:14 UTC, Hamitix commented on lib/shared/toast_utils.dart
> +
Arrow return function =>

2022-09-20 14:14 UTC, Hamitix commented on lib/shared/toast_utils.dart
> +}
Maybe merge these 2 functions into one, with "isSuccess" boolean ?

2022-09-20 14:14 UTC, Hamitix commented on lib/shared/toast_utils.dart
> +  Timer.run(() => _showAlert(
is Timer.run really needed here ?

2022-09-21 07:05 UTC, Hamitix approved these changes
LGTM :)

2022-09-21 07:05 UTC, merged